name = "kings-league-api"
main = "api/index.ts"
compatibility_date = "2023-01-19"

[site]
bucket = "./assets"

[env.production]
vars = { ENVIRONMENT = "production" }
routes = [
  { pattern = "kings-league-api.carlos8alb.workers.dev", custom_domain = true }
]